### ISSUE TITLE
Scenes aren't synced

### ISSUE THREAD

**Issue by CodeRhymesLife** [webaverse/multiplayer#1]
When I enter VR then grab and move around the scene, other clients don't get the updated scene position.

**Comment by avaer** [comment]
Thanks, could you be more specific about moving around the scene? What is being grabbed?

I just tried connecting and it worked.

![Screen Shot 2020-07-01 at 11 48 40 PM](https://user-images.githubusercontent.com/6926057/86314392-8cb0cc80-bbf5-11ea-9edc-06eb5c563857.png)

Note that objects aren't synced unless they are dragged under the multiplayer object.

**Comment by CodeRhymesLife** [comment]
I may misunderstand what's happening. In the gif below I have two browser tabs with the multiplayer XRPackage loaded, a sword and a blob. The tab on the left is rendering in steamvr as an overlay. I'm using the grip button to grab the sword and blob. As I move them around they don't change position in the right browser tab like I expected them to.

![scene sync](https://user-images.githubusercontent.com/2764891/86317811-3a67af80-bbe5-11ea-8775-893f7ba7eb23.gif)

Would you mind explaining your image?

**Comment by avaer** [comment]
My image just has one multiplayer package loaded in two tabs, so the avatars are synced. There are no objects.

Multiplayer does not sync _everything_ by default at the moment, only the things that are dragged under the multiplayer object as children of the multiplayer object in the right hand side UI.

Also note that we never mirror the VR view back to the browser -- that we never a feature we had. We might want to add it.

**Comment by avaer** [comment]
I suspect what you are asking for is to make sure multiplayer is loaded in both tabs, and then drag the objects you want to sync underneath the multiplayer package in the 2D ui.

**Comment by CodeRhymesLife** [comment]
Got it. I'm doing a hackathon at Pluto. Our project is to get multiplayer clients synced while VR, so we're looking to contribute that. If you have any pointers please let me know.

**Comment by CodeRhymesLife** [comment]
BTW, in the gif above both the sword and blob are under the multiplayer object.

**Comment by avaer** [comment]
Ah ok yeah, that might be bugged.

If you see here, the object matrices are being emitted: https://github.com/webaverse/multiplayer/blob/3705960082c168a6b7634c2e5cb19d29ed523f05/index.html#L576

We should probably be emitting the objects as their matrices change and detecting the change on clients (https://github.com/webaverse/multiplayer/blob/3705960082c168a6b7634c2e5cb19d29ed523f05/index.html#L448).

Additionally, if message shapes need to change I would recommend spinning up a dialog server (https://github.com/webaverse/dialog/pull/1) as the backend for testing, which is passed to `XRChannelConnection`.

**Comment by CodeRhymesLife** [comment]
Sounds good. I'll give that a try. Thanks for the pointers and sorry about the lack of detail initially.

**Comment by CodeRhymesLife** [comment]
Dug into this a bit more. I noticed edit UI has a panel for updating the position of packages here:

https://github.com/webaverse/xrpackage-site/blob/4e0afbc0a2611a1f32ce4bdce33806d197b70053/edit.js#L1928

When the xrpackage position (matrix) is updated `setMatrix` is called here:

https://github.com/webaverse/xrpackage-site/blob/4e0afbc0a2611a1f32ce4bdce33806d197b70053/edit.js#L1931

`setMatrix` internally dispatches the 'matrixupdate' event here:

https://github.com/webaverse/xrpackage/blob/b20d2595c0e01dca1620090df4ca7d6fc21f94bf/xrpackage.js#L2188

The multiplayer XRPackage is listening for the 'matrixupdate' event here, but it never gets called:

https://github.com/webaverse/multiplayer/blob/3705960082c168a6b7634c2e5cb19d29ed523f05/index.html#L477

If we hooked that up it seems like objects would start syncing. What do you think of that approach?

**Comment by avaer** [comment]
> The multiplayer XRPackage is listening for the 'matrixupdate' event here, but it never gets called:

I think it isn't being listened to on the right `EventTarget`. It is listening on the top level multiplayer package rather than the child package.

> If we hooked that up it seems like objects would start syncing. What do you think of that approach?

Yes I think that's the right approach.
